from __future__ import annotations

# Standardized observability reason codes for core safety events.
RISKY_ORDER_BLOCK = "RISKY_ORDER_BLOCK"
STARTUP_BLOCKED = "STARTUP_BLOCKED"
HALT_ENTERED = "HALT_ENTERED"
CANCEL_FAILURE = "CANCEL_FAILURE"
RECONCILE_MISMATCH = "RECONCILE_MISMATCH"
SUBMIT_TIMEOUT = "SUBMIT_TIMEOUT"
AMBIGUOUS_SUBMIT = "AMBIGUOUS_SUBMIT"
SUBMIT_FAILED = "SUBMIT_FAILED"
WEAK_ORDER_CORRELATION = "WEAK_ORDER_CORRELATION"
AMBIGUOUS_RECENT_FILL = "AMBIGUOUS_RECENT_FILL"
POSITION_LOSS_LIMIT = "POSITION_LOSS_LIMIT"
DUST_RESIDUAL_UNSELLABLE = "DUST_RESIDUAL_UNSELLABLE"
EXIT_PARTIAL_LEFT_DUST = "EXIT_PARTIAL_LEFT_DUST"
MANUAL_DUST_REVIEW_REQUIRED = "MANUAL_DUST_REVIEW_REQUIRED"

EMERGENCY_FLATTEN_STARTED = "EMERGENCY_FLATTEN_STARTED"
EMERGENCY_FLATTEN_SUCCEEDED = "EMERGENCY_FLATTEN_SUCCEEDED"
EMERGENCY_FLATTEN_FAILED = "EMERGENCY_FLATTEN_FAILED"
