from __future__ import annotations

# Standardized observability reason codes for core safety events.
RISKY_ORDER_BLOCK = "RISKY_ORDER_BLOCK"
STARTUP_BLOCKED = "STARTUP_BLOCKED"
HALT_ENTERED = "HALT_ENTERED"
CANCEL_FAILURE = "CANCEL_FAILURE"
RECONCILE_MISMATCH = "RECONCILE_MISMATCH"
SUBMIT_TIMEOUT = "SUBMIT_TIMEOUT"
AMBIGUOUS_SUBMIT = "AMBIGUOUS_SUBMIT"
SUBMIT_FAILED = "SUBMIT_FAILED"
WEAK_ORDER_CORRELATION = "WEAK_ORDER_CORRELATION"
AMBIGUOUS_RECENT_FILL = "AMBIGUOUS_RECENT_FILL"
POSITION_LOSS_LIMIT = "POSITION_LOSS_LIMIT"
DUST_RESIDUAL_UNSELLABLE = "DUST_RESIDUAL_UNSELLABLE"
DUST_RESIDUAL_SUPPRESSED = "DUST_RESIDUAL_SUPPRESSED"
EXIT_PARTIAL_LEFT_DUST = "EXIT_PARTIAL_LEFT_DUST"
MANUAL_DUST_REVIEW_REQUIRED = "MANUAL_DUST_REVIEW_REQUIRED"

# SELL failure categories used by operator-facing reporting and audit evidence.
SELL_FAILURE_CATEGORY_QTY_STEP_MISMATCH = "qty_step_mismatch"
SELL_FAILURE_CATEGORY_BOUNDARY_BELOW_MIN = "boundary_below_min"
SELL_FAILURE_CATEGORY_DUST_RESIDUAL_UNSELLABLE = "dust_residual_unsellable"
SELL_FAILURE_CATEGORY_UNSAFE_DUST_MISMATCH = "unsafe_dust_mismatch_dust"
SELL_FAILURE_CATEGORY_REMAINDER_DUST_GUARD = "remainder_dust_guard"
SELL_FAILURE_CATEGORY_DUST_SUPPRESSION = "dust_suppression"
SELL_FAILURE_CATEGORY_SUBMISSION_HALT = "submission_halt"
SELL_FAILURE_CATEGORY_UNRESOLVED_RISK_GATE = "unresolved_risk_gate"
SELL_FAILURE_CATEGORY_UNKNOWN = "unknown"

EMERGENCY_FLATTEN_STARTED = "EMERGENCY_FLATTEN_STARTED"
EMERGENCY_FLATTEN_SUCCEEDED = "EMERGENCY_FLATTEN_SUCCEEDED"
EMERGENCY_FLATTEN_FAILED = "EMERGENCY_FLATTEN_FAILED"
