from __future__ import annotations

# Standardized observability reason codes for core safety events.
RISKY_ORDER_BLOCK = "RISKY_ORDER_BLOCK"
STARTUP_BLOCKED = "STARTUP_BLOCKED"
HALT_ENTERED = "HALT_ENTERED"
CANCEL_FAILURE = "CANCEL_FAILURE"
RECONCILE_MISMATCH = "RECONCILE_MISMATCH"
SUBMIT_TIMEOUT = "SUBMIT_TIMEOUT"
AMBIGUOUS_SUBMIT = "AMBIGUOUS_SUBMIT"
SUBMIT_FAILED = "SUBMIT_FAILED"
WEAK_ORDER_CORRELATION = "WEAK_ORDER_CORRELATION"
AMBIGUOUS_RECENT_FILL = "AMBIGUOUS_RECENT_FILL"
